# Generated by Django 6.0.1 on 2026-01-28 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='car_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='driver_license',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
