# Generated by Django 6.0.1 on 2026-01-28 23:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_person_car_number_person_driver_license'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='car_number',
        ),
        migrations.RemoveField(
            model_name='person',
            name='driver_license',
        ),
    ]
