# Generated by Django 6.0.1 on 2026-01-29 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_remove_person_car_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='token',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
