# Generated by Django 6.0.1 on 2026-01-29 20:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_person_token'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='token',
        ),
    ]
