# Generated by Django 6.0.1 on 2026-01-29 20:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ratings', '0002_alter_rating_unique_together_alter_rating_ride'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rating',
            name='reviewee',
        ),
        migrations.RemoveField(
            model_name='rating',
            name='reviewer',
        ),
    ]
